# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [1]:
import numpy as np

In [2]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [3]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''
np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(5, 6, 6)
W = np.random.randn(5, 6, 6)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = 11.602725933576108


In [4]:
a_slice_prev

array([[[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,
          0.86540763, -2.3015387 ],
        [ 1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
          1.46210794, -2.06014071],
        [-0.3224172 , -0.38405435,  1.13376944, -1.09989127,
         -0.17242821, -0.87785842],
        [ 0.04221375,  0.58281521, -1.10061918,  1.14472371,
          0.90159072,  0.50249434],
        [ 0.90085595, -0.68372786, -0.12289023, -0.93576943,
         -0.26788808,  0.53035547],
        [-0.69166075, -0.39675353, -0.6871727 , -0.84520564,
         -0.67124613, -0.0126646 ]],

       [[-1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
         -0.19183555, -0.88762896],
        [-0.74715829,  1.6924546 ,  0.05080775, -0.63699565,
          0.19091548,  2.10025514],
        [ 0.12015895,  0.61720311,  0.30017032, -0.35224985,
         -1.1425182 , -0.34934272],
        [-0.20889423,  0.58662319,  0.83898341,  0.93110208,
          0.28558733,  0.88514116],
        [-0.75439794,  1.252

In [6]:
s = a_slice_prev * W
s

array([[[-2.06707491e+00, -1.91814829e-01, -2.65768005e-01,
         -1.38759079e+00, -9.55816993e-02,  1.42088268e+00],
        [ 9.81912182e-01, -1.83250736e-01,  8.95431325e-02,
          1.82321424e-02,  1.69654023e+00, -7.61206987e-01],
        [-6.14094735e-01, -4.26706163e-01,  7.47210520e-01,
          1.79000522e+00, -1.03856834e-01, -3.68948270e-01],
        [ 3.42333085e-02,  6.08716743e-01,  4.41214226e-01,
          9.43258768e-01, -5.06969359e-01,  9.82315166e-01],
        [-1.19989658e+00,  1.20383182e+00,  2.02857509e-01,
          8.33354695e-01,  2.99797675e-01,  1.03741714e+00],
        [ 2.25826888e-01,  5.32711355e-01, -7.65773559e-01,
          4.95733342e-01,  8.30233043e-01, -1.10921487e-02]],

       [[-6.96489011e-01, -1.01960674e-01,  2.33623796e+00,
          9.57990733e-02, -3.10188419e-01, -4.46247368e-01],
        [-1.16467449e+00,  1.85159097e-01, -6.19724742e-02,
         -1.56023717e+00, -1.04196740e-01, -4.17610243e-01],
        [-8.41591507e-02, -1.2

In [7]:
Z

11.602725933576108

In [8]:
b

array([[[-0.55749472]]])